<?xml version='1.0'?>

<robot name="wheelchair" xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <xacro:property name="cameraSize" value="0.05"/>
  <xacro:property name="cameraMass" value="0.1"/>

  <xacro:property name="PI" value="3.14" />
  <xacro:property name="PI_Half" value="1.5707" />

  <xacro:property name="chair_width" value="0.643" /> <!-- From front wheel right joint to front wheel left joint -->
  <xacro:property name="chair_length" value="0.812" /> <!-- From front wheel joint to back wheel joint -->
  <xacro:property name="chair_height" value="1.191" /> <!-- From front wheel joint to head rest -->
  <xacro:property name="chair_weight" value="10.0" />


  <xacro:property name="legs_width" value="0.4064" />
  <xacro:property name="legs_length" value="0.4064" />
  <xacro:property name="legs_height" value="0.4064" />
  <xacro:property name="legs_weight" value="2.0" />

  <xacro:property name="main_wheel_length" value="0.0356884" />
  <xacro:property name="main_wheel_radius" value="0.201784" />
  <xacro:property name="main_wheel_weight" value="3.0" />

  <xacro:property name="small_wheel_radius" value="0.068" />
  <xacro:property name="small_wheel_length" value="0.032" />
  <xacro:property name="small_wheel_weight" value="1.0" />

  <xacro:include filename="$(find robot_sim)/urdf/materials.xacro" />
  <xacro:include filename="$(find robot_sim)/urdf/macros.xacro" />


  <link name='base_chassis'>
    <pose>0 0 0.201784 0 0 0</pose>
    <inertial>
      <mass value="10.0"/>
      <origin xyz="0 0 0.201784" rpy=" 0 0 0"/>
      <box_inertia m="2" x="0.01" y="0.01" z ="0.406054" />
    </inertial>
    <collision name='collision'>
      <geometry>
        <box size="0.01 0.406054 0.01"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 -3.14"/>
      <geometry>
         <mesh filename="package://robot_sim/meshes/wheelchair_chasis.stl" scale="0.01 0.01 0.01"/>
      </geometry>
  </visual>
  <visual>
    <origin xyz="0 0 0.201784" rpy="0 0 0"/>
    <geometry>
      <box size="0.01 0.406054 0.01"/>
    </geometry>
</visual>
</link>
  <!--
  <chassis name="base" xyz="0 0 ${main_wheel_radius}" rpy="0 0 0" m="2" chassisLength="0.01" chassisWidth="${2*main_wheel_radius}" chassisHeight="0.01"/>
-->
  <chassis name="os" xyz="${3/4*main_wheel_radius} 0.01 0.01" rpy="0 0 0" m="2" chassisLength="${3/2*main_wheel_radius}" chassisWidth="0.01" chassisHeight="0.01"/>
  <link_joint parent="base_chassis" child ="os_chassis" xyz="0 0 ${main_wheel_radius}" rpy="0 0 0" />

  <chassis name="os1" xyz="${3/4*main_wheel_radius} 0 ${main_wheel_radius}" rpy="0 0 0" m="2" chassisLength="0.01" chassisWidth="${2*main_wheel_radius - 0.2}" chassisHeight="0.01"/>
  <link_joint parent="os_chassis" child ="os1_chassis" xyz="${3/4*main_wheel_radius} 0 0" rpy="0 0 0" />

  <chassis name="os2" xyz="0 0 ${-main_wheel_radius/4}" rpy="0 0 0" m="2" chassisLength="0.01" chassisWidth="0.01" chassisHeight="${main_wheel_radius/2}"/>
  <link_joint parent="os1_chassis" child ="os2_chassis" xyz="${3/4*main_wheel_radius} ${main_wheel_radius/2} 0" rpy="0 0 0" />
  <chassis name="os3" xyz="0 0 ${-main_wheel_radius/4}" rpy="0 0 0" m="2" chassisLength="0.01" chassisWidth="0.01" chassisHeight="${main_wheel_radius/2}"/>
  <link_joint parent="os1_chassis" child ="os3_chassis" xyz="${3/4*main_wheel_radius} ${-main_wheel_radius/2} 0" rpy="0 0 0" />



  <wheel  lr="l" tY="0.02" xyz=" 0 0 0" rpy="${-pi/2} 0 0" wheelWidth="${main_wheel_length}" wheelRadius="${main_wheel_radius}" wheelMass="${main_wheel_weight}" meshFile="wheelchair_wheel"/>
  <wheel_joint parent="base_chassis" child ="l_wheel" xyz="0 ${main_wheel_radius} ${main_wheel_radius}" rpy="0 0 0" />
  <wheel  lr="r" tY="0.02" xyz=" 0 0 0" rpy="${pi/2} 0 0" wheelWidth="${main_wheel_length}" wheelRadius="${main_wheel_radius}" wheelMass="${main_wheel_weight}" meshFile="wheelchair_wheel"/>
  <wheel_joint parent="base_chassis" child ="r_wheel" xyz="0 ${-main_wheel_radius} ${main_wheel_radius}" rpy="0 0 0" />

  <wheel  lr="lf" tY="0.001" xyz=" 0 0 0" rpy="${pi/2} 0 0" wheelWidth="${small_wheel_length}" wheelRadius="${small_wheel_radius}" wheelMass="${small_wheel_weight}" meshFile="wheelchair_wheel_front"/>
  <wheel_joint parent="os2_chassis" child ="lf_wheel" xyz="0 ${-main_wheel_radius} ${small_wheel_radius}" rpy="0 0 0" />

  <wheel  lr="lr" tY="0.001" xyz=" 0 0 0" rpy="${pi/2} 0 0" wheelWidth="${small_wheel_length}" wheelRadius="${small_wheel_radius}" wheelMass="${small_wheel_weight}" meshFile="wheelchair_wheel_front"/>
  <wheel_joint parent="os3_chassis" child ="lr_wheel" xyz="0 ${main_wheel_radius} ${small_wheel_radius}" rpy="0 0 0" />


  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <legacyMode>false</legacyMode>
      <alwaysOn>true</alwaysOn>
      <updateRate>20</updateRate>
      <leftJoint>base_chassis_l_wheel_joint</leftJoint>
      <rightJoint>base_chassis_r_wheel_joint</rightJoint>
      <wheelSeparation>2*main_wheel_radius</wheelSeparation>
      <wheelDiameter>2*main_wheel_radius</wheelDiameter>
      <torque>20</torque>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_chassis</robotBaseFrame>
    </plugin>
  </gazebo>

  <gazebo reference="chassis">
      <material name="green">
    	<color rgba="0.0 0.8 0.0 1.0"/>
      </material>
  </gazebo>


</robot>
